/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BaseModuleGuard } from "./BaseModuleGuard";
export type { IModuleGuard } from "./IModuleGuard";
export type { ModuleManager } from "./ModuleManager";
