/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC1155TokenReceiver } from "./ERC1155TokenReceiver";
export type { ERC721TokenReceiver } from "./ERC721TokenReceiver";
export type { ERC777TokensRecipient } from "./ERC777TokensRecipient";
export type { IERC165 } from "./IERC165";
export type { ISignatureValidator } from "./ISignatureValidator";
export type { ViewStorageAccessible } from "./ViewStorageAccessible";
