/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as gnosisSafeProxySol from "./GnosisSafeProxy.sol";
export { GnosisSafeProxyFactory__factory } from "./GnosisSafeProxyFactory__factory";
export { IProxyCreationCallback__factory } from "./IProxyCreationCallback__factory";
