/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  NativeCurrencyPaymentFallback,
  NativeCurrencyPaymentFallbackInterface,
} from "../../../contracts/common/NativeCurrencyPaymentFallback";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "value",
        type: "uint256",
      },
    ],
    name: "SafeReceived",
    type: "event",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

export class NativeCurrencyPaymentFallback__factory {
  static readonly abi = _abi;
  static createInterface(): NativeCurrencyPaymentFallbackInterface {
    return new Interface(_abi) as NativeCurrencyPaymentFallbackInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): NativeCurrencyPaymentFallback {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as NativeCurrencyPaymentFallback;
  }
}
