/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EtherPaymentFallback } from "./EtherPaymentFallback";
export type { StorageAccessible } from "./StorageAccessible";
