/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CompatibilityFallbackHandler } from "./CompatibilityFallbackHandler";
export type { ISafe } from "./ISafe";
